### PR TITLE
ESC3 Condition 1 Checks

### PR DESCRIPTION
**Pull request by TrimarcJake**
ESC3 Condition 1 Checks in Locksmith
ESC3 Condition 1 template generation in Invoke-TSS.ps1
Slight name changes in Format-Result

### CODE REVIEW

**Comment by techspence** [comment]
I tested this. Works great! Do you think it makes sense to get more granular with the issue technique? For example, this would be ESC3C1 (for condition 1). The output would then look something like this:

Technique: ESC3C1
Name: Super Secure Enrollment Agent                         
Issue: NT AUTHORITY\Authenticated Users can enroll in this Enrollment Agent template without Manager Approval

**Comment by SamErde** [comment]
> I tested this. Works great! Do you think it makes sense to get more granular with the issue technique? For example, this would be ESC3C1 (for condition 1). The output would then look something like this:
> 
> Technique: ESC3C1 Name: Super Secure Enrollment Agent Issue: NT AUTHORITY\Authenticated Users can enroll in this Enrollment Agent template without Manager Approval

My gut reaction is to keep our output aligned as tightly as possible with the ESC* source material. In my mind, that looks like still showing it as a "ESC3" but with a new 'Condition' attribute on the output Issue object.

**Comment by TrimarcJake** [comment]
I think that makes sense, @SamErde. (Sorry @techspence).

Once that's in place, we can begin taking Conditions into account when determining priority. For example:

- One (1) ESC3C1 template + zero (0) ESC3C2 templates = Medium priority 
- Zero (0) ESC3C1 templates + one (1) ESC3C2 = Low priority
- One (1) ESC3C1 template scoped to Domain Users + one (1) ESC3C2 = Critical priority
- One (1) of each template and both are scoped to small groups = Medium priority

**Review by techspence — APPROVED** [review]
Good to go!

**Pull request merged**
