### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by SamErde**
Noticed we don't have templates for issues, bug reports, or feature requests.

### CODE REVIEW

**Comment by TrimarcJake** [comment]
I'll review yours if you review mine.

**Comment by SamErde** [comment]
BlueTuxedo? 😉

**Comment by TrimarcJake** [comment]
There is no BlueTuxedo here! (I'll review soon.)

**Review by TrimarcJake — APPROVED** [review]
Approval = very yes.

**Pull request merged**
