### PR TITLE
Finding Flowcharts To Feed Severity Ratings

### PR DESCRIPTION
**Pull request by TrimarcJake**
In order to build out automated severity ratings, we need to know what the severities are first! Then we can build code to match. These should help.

### CODE REVIEW

**Comment by SamErde** [comment]
Nice! The docs and visuals should help a lot. I haven't had a chance to review the actual flow for each severity evaluation yet, but the rest looks great.

One question: would it be worth creating a future-proof 'Docs' folder that contains 'Flowcharts' as well as any future documentation that is created (or generated with platyPS)?

**Comment by TrimarcJake** [comment]
I think the flowcharts are just a starting point, so if you like the way they look, we should merge them. We can iterate on them as we build more subtle rating methods.

"Docs" does make more sense, tho! Maybe a structure like this:

Screenshot 2024-02-29 at 8 47 27 PM

```
~/iCloud Drive/Development/PowerShell/Locksmith/Docs finding-flowcharts* ⇣
❯ tree
.
└── Flowcharts
    ├── Auditing.md
    ├── ESC1.md
    ├── ESC2.md
    ├── ESC3.md
    ├── ESC4.md
    ├── ESC5.md
    ├── ESC6.md
    └── ESC8.md
```

**Comment by techspence** [comment]
Really nice work. I think these flowcharts are a great addition to the project! Question: Do we think having a key or a glossary to explain some of these terms may be useful to folks _not_ super familiar with these concepts? Or maybe just clarify what we mean? Such as BuiltIn/PKI Admin, AD Admin. It may be utterly trivial, just thinking edge cases with terminology.

**Review by SamErde — APPROVED** [review]

**Comment by TrimarcJake** [comment]
> Really nice work. I think these flowcharts are a great addition to the project! Question: Do we think having a key or a glossary to explain some of these terms may be useful to folks _not_ super familiar with these concepts? Or maybe just clarify what we mean? Such as BuiltIn/PKI Admin, AD Admin. It may be utterly trivial, just thinking edge cases with terminology.

Yeah, I think a glossary is a great idea now that we have a Docs folder! :D

**Pull request merged**
