### PR TITLE
Update Invoke-Scans.ps1

### PR DESCRIPTION
**Pull request by brokenvhs**
I believe there may be a bug in the invoke-scans.ps1 file. When running individual scans, the array being used for ESC13, ESC15 and EKUwu are all set to $ESC11. I noticed this while debugging after receiving unexpected results.

In my proposed fix, I changed the array variables on the individual ESC13, 15, and EKUwu to what I believe their respective arrays should be.

### CODE REVIEW

**Review by TrimarcJake — APPROVED** [review]
Ol' copy and paste programming strikes again. Nice catch!

**Comment by TrimarcJake** [comment]
Thank you so much for your catch!

**Comment by brokenvhs** [comment]
> Thank you so much for your catch!

No Problem.

The same issue is in the Invoke-Locksmith.ps1 monolithic script, I wasn't sure what your process was for merging the module into that, but I should have probably included it here as well.

**Comment by TrimarcJake** [comment]
I always build a fresh copy of the monolithic script before merging changes into the `testing` branch, so this will be handled probably tonight!

**Comment by brokenvhs** [comment]
I found a couple of other issues. In the future, do you prefer a separate PR for each issue? I am submitting a PR for one right now and based on your reply can submit another or just let you make the switch if necessary. 

One of them may not be an issue and could be intended: I noticed the PreScriptMerge in Build-Modules has not been updated for the new arguments -OutputPath and -Credential, and do not include ESC13, 15/EKUwu in the -Scans parameter, so if you run the monolithic script you are not able to use those arguments or those newer scans.

**Comment by TrimarcJake** [comment]
A separate PR for each is definitely preferred. Fewer changes in a PR means there's less chance for error. 

I will say to make sure you are working against the `testing` branch. We've settled on a branch strategy where `main` will always be stable(-ish) but fixes and new features will be built in `testing`. I think a few of the issues you mention have already been fixed.

Maybe.

I'm on my phone right now and it is *not* conducive to code review. 😃 

Thank you!

**Comment by SamErde** [comment]
Great call on the separate PRs. My PR from earlier this evening partially fixes a bit of what you mentioned, but not all of it yet. Great observation!

**Pull request merged**
