### PR TITLE
Proper PowerShell module with build script preconfigured

### PR DESCRIPTION
**Pull request by PrzemyslawKlys**
Hi, 

I like your little project and since I have written several similar projects to yours over the years I've built a habbit of creating PowerShell modules instead of simple scripts, that can be redistributed via PowerShellGallery for easy of use. While working on my modules I wrote a PowerShell module builder called [PSPublishModule](https://github.com/EvotecIT/PSPublishModule) that's main goal is to automate creation of modules. Since I maintain over 70 PowerShell modules I need fully automated process around it. 

The module doesn't have much documentation, so it's not well known. I will be creating a blog post about it soon, for the larger PowerShell community to help "convert" scripts to modules, but I also thought on writting a blog post by using an example module. And to do so - I've chosen your little project to help you. 

Feel free to use it, or not use it. I do hope I've not stepped over any boundaries here - just thought this will be useful for you and general PowerShell / AD / PKI community. 

I believe the structure I've created, and the Build-Module.ps1 is very simple to use.

- Private - folder with all your private functions that are 'hidden' for users - I've moved all functions there that I believe are private - creating one file, per each function
- Public - folder with all your public functions that are available to use for users - I've moved only your main code there. 
- Build - contains build-module - when you run it - you get this:

image
image

It basically creates PSM1/PSD1 version of the Private/Public data, merges it and makes it available in the system. 
I've also preconfigured it to create Artefacts folder, one that packs your release under .zip, and one that just has merged version. 

image

This setup allows you to work on development on function per file basis which is easier to read and maintain, but when it comes to publishing to PSGallery, or using on production it provides a single file which is faster and optimized. 

I've also noticed other things that would be good to fix, but before I spend any time on it I thought I would push this and let you decide whether this is at all helpful and you like this direction, or you prefer to continue your own way. 

For me this is good exercise to showcase my module builder in action, and maybe you will benefit of it. 

Couple of things I noticed that you may want to address:
- You are using Clear-Host, when you shouldn't. If you get errors, clear host will hide them. I understand the use case, but it's bad practice, that you should avoid
- Using Set-StrictMode should be avoided in production version of code - you can use it in dev, but it doesn't bring much benefits. You will be much safer avoiding it
- You are building objects using `New-object` which is slow/ugly/inefficient

For example:

```powershell
$Issue = New-Object -TypeName pscustomobject
$Issue | Add-Member -MemberType NoteProperty -Name Forest -Value $_.CanonicalName.split('/')[0] -Force
$Issue | Add-Member -MemberType NoteProperty -Name Name -Value $_.Name -Force
$Issue | Add-Member -MemberType NoteProperty -Name DistinguishedName -Value $_.DistinguishedName -Force
if ($_.CAEnrollmentEndpoint -like '^http*') {
    $Issue | Add-Member -MemberType NoteProperty -Name Issue -Value 'HTTP enrollment is enabled.' -Force
    $Issue | Add-Member -MemberType NoteProperty -Name CAEnrollmentEndpoint -Value $_.CAEnrollmentEndpoint -Force
    $Issue | Add-Member -MemberType NoteProperty -Name Fix -Value "TBD - Remediate by doing 1, 2, and 3" -Force
    $Issue | Add-Member -MemberType NoteProperty -Name Revert -Value "TBD" -Force
} else {
    $Issue | Add-Member -MemberType NoteProperty -Name Issue -Value 'HTTPS enrollment is enabled.' -Force
    $Issue | Add-Member -MemberType NoteProperty -Name CAEnrollmentEndpoint -Value $_.CAEnrollmentEndpoint -Force
    $Issue | Add-Member -MemberType NoteProperty -Name Fix -Value "TBD - Remediate by doing 1, 2, and 3" -Force
    $Issue | Add-Member -MemberType NoteProperty -Name Revert -Value "TBD" -Force
}
$Issue | Add-Member -MemberType NoteProperty -Name Technique -Value 'ESC8'
$Issue
```

Can be replaced by:

```powershell
function Find-ESC8 {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $ADCSObjects
    )
    process {
        $ADCSObjects | Where-Object {
            $_.CAEnrollmentEndpoint
        } | ForEach-Object {
            $Issue = [ordered] @{
                Forest            = $_.CanonicalName.split('/')[0]
                Name              = $_.Name
                DistinguishedName = $_.DistinguishedName
            }
            if ($_.CAEnrollmentEndpoint -like '^http*') {
                $Issue['Issue'] = 'HTTP enrollment is enabled.'
                $Issue['CAEnrollmentEndpoint'] = $_.CAEnrollmentEndpoint
                $Issue['Fix'] = 'TBD - Remediate by doing 1, 2, and 3'
                $Issue['Revert'] = 'TBD'
            } else {
                $Issue['Issue'] = 'HTTPS enrollment is enabled.'
                $Issue['CAEnrollmentEndpoint'] = $_.CAEnrollmentEndpoint
                $Issue['Fix'] = 'TBD - Remediate by doing 1, 2, and 3'
                $Issue['Revert'] = 'TBD'
            }
            $Issue['Technique'] = 'ESC8'
            [PSCustomObject] $Issue
        }
    }
}
```

You can also built directly PSCustomObject

```powershell
[PSCustomObject] @{
    Forest            = $_.CanonicalName.split('/')[0]
    Name              = $_.Name
    DistinguishedName = $_.DistinguishedName
}
```

The difference is - you won't be able to attach any new properties to it, unless you use Add-Member which is slow, and that's why I've used ordered dictionary as above.

- You are saying you want PowerShell version 3 as minimum, yet you use `Get-LocalUser` in code. This cmdlet comes as part Windows 10 / PS 5.1. I think you can fully skip requiring anything else then 5.1 tho, as defined in PSD1. 

Ah, to get yourself running with this you need:

```powershell
Install-Module PSPublishModule -Force -Verbose
```

Hope this helps. If you have any questions/problems, please let me know. I'll try to help.

### CODE REVIEW

**Comment by TrimarcJake** [comment]
Holy smokes. This is incredible work!

I **think** I'm fully on board with what you've proposed here, but I'll need to spend some time really digesting everything to ensure it makes sense for the project going forward. And I'll need to chat with the other two members of the core team to make sure we **all** understand the implications.

BTW: I greatly appreciate the tips you provided at the end! I'm sure you can tell, but everyone submitting code for this is much less experienced than you. Having a seasoned pro take interest in the project is awesome.

**Comment by PrzemyslawKlys** [comment]
The change is:
- It's easier to provide PR's because you modify or add new code without breaking other peoples code - so it's much less hassle to deal with
- It's easier to develop new functions, because you are not working with file that's 2000 lines of code, but more like 10-200.
- It's easier to spot bugs

The problems from this:
- When you run code while in "code"/ISE you have to first call "Import-Module .\Locksmith.psd1 -force" before you try your code. This makes sure that all the functions, and everything gets reloaded, if you don't you may be working with "old" version of files
- When functions are private, they are not exposed for users, but also for you. This means if you just want to test this specific function you may need to reconfigure build to make sure that all your functions are exposed (don't worry, it's only exposing it in the "development PSD1", not the merged one that's for publishing. I also have this fully automated switch which takes care of it:

image

Once you enable it, it changes `FunctionsToExport` to all functions from Private and all from Public. 

image

Changing it back, fixes PSD1 to only the public one. 


For working with code you would essentially do something like this:

image

This would make sure that changes you did in Public/Private folders are reloaded for you to use them 

I actually commented out Clear-Host because I saw red color fly by and this is what I get: 

image

As said before - Clear-Host is no-go in modules/scripts. Especially since users may not want to clear anything they had in their console, and you should respect that.

**Comment by TrimarcJake** [comment]
I appreciate you taking the time to go through all this with me. Are you available to chat if I have questions? 

Also, would you like to collaborate on the blog article you’ve described?

**Comment by PrzemyslawKlys** [comment]
I have 2 blogs coming:
- Simplifying module building and PowerShell Gallery Integration
- Converting Trimarc Locksmith script to fully fledge PowerShell module

Those will be published on: https://evotec.xyz/hub/ - as I am the only person blogging on it, and never had anyone else help me with my blogs I am not sure how to "collaborate" :-) So if you have anything on your mind - happy to hear it.

The first one is supposed to talk about the module itself and what are the commands, what options there are, things like that. Maybe touch a bit about features that are unique to this module. For example when you first run it on your code, it detects your dependencies such as Active Directory and other modules that should be included in the PSD1 package. 

image

It won't let you thru until you actually deal with it in some way. Either add it to required modules, or skip them because those are part of PowerShell itself. 

The second blog post so far is just a screenshots of me converting your script on different phases that I will try to describe what I did and why. 

Since I made step A, I am ready for step B to help you answer the questions if you have any. Since there's very few people using the my module builder, as there is no documentation on it aside from couple of examples. You can find me on twitter, bluesky, linkedin, powershell discord (https://aka.ms/psdiscord) which is useful by itself, as there's plenty of people that help on a daily basis.

**Pull request closed without merging**
